name: insurance-pinn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly        # remove this line if you want CUDA support
  - plotly
  - jupyterlab
  - pip
  - pip:
      - tqdm
